export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'


export const ADD_ADVENTURE_FAILURE = 'ADD_ADVENTURE_FAILURE'
export const ADD_ADVENTURE = 'ADD_ADVENTURE'
